### ISSUE TITLE
error running example molniya plot

### ISSUE THREAD

**Issue by cajunlyceum** [poliastro/poliastro#1177]
from a fresh install of poliastro:

(base) jasonb@tookville:~/PycharmProjects/udluploads/venv$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from poliastro.examples import molniya
>>> molniya.plot()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jasonb/anaconda3/lib/python3.7/site-packages/poliastro/twobody/orbit.py", line 1435, in plot
    return StaticOrbitPlotter().plot(self, label=label)
  File "/home/jasonb/anaconda3/lib/python3.7/site-packages/poliastro/plotting/static.py", line 213, in plot
    self.set_orbit_frame(orbit)
  File "/home/jasonb/anaconda3/lib/python3.7/site-packages/poliastro/plotting/_base.py", line 343, in set_orbit_frame
    self._set_frame(*orbit.pqw())
  File "/home/jasonb/anaconda3/lib/python3.7/site-packages/poliastro/twobody/orbit.py", line 1146, in pqw
    p_vec = self.e_vec / self.ecc
  File "/home/jasonb/anaconda3/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jasonb/anaconda3/lib/python3.7/site-packages/poliastro/twobody/orbit.py", line 191, in e_vec
    r, v = self.rv()
  File "/home/jasonb/anaconda3/lib/python3.7/site-packages/poliastro/twobody/orbit.py", line 1118, in rv
    return self.r, self.v
  File "/home/jasonb/anaconda3/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jasonb/anaconda3/lib/python3.7/site-packages/poliastro/twobody/orbit.py", line 96, in r
    return self._state.to_vectors().r
  File "/home/jasonb/anaconda3/lib/python3.7/site-packages/poliastro/twobody/states.py", line 137, in to_vectors
    self.nu.to(u.rad).value,
TypeError: expected dtype object, got 'numpy.dtype[float64]'

**Comment by DhruvSondhi** [comment]
Hello @cajunlyceum ... Welcome to _**poliastro**_ 🚀 ... There are some things that I would like to inquire before suggesting any solutions for the problem 
1. Can you please attach the output of `conda list` (looks like you are on a Conda Environment 👀)?

From the error you have been presented with, it seems so that `Numpy` is the problem.
>TypeError: expected dtype object, got 'numpy.dtype[float64]'

I would suggest that you install `Numpy version 0.19.5` which can be done from the command `conda install numpy=0.19.5` ... Please do confirm the same if this fixes the issue 😄 ... Cheers 🚀

**Comment by Yash-10** [comment]
Hello @cajunlyceum thank you for the issue!

From the `TypeError` it seems that the problem is the `numba` version.

I strongly suspect you might have an older `numba` version but a newer `numpy` version, as a result of which this error might have occured.

Could you please install the latest `numba` version (any version `>= 0.52` would work) and try running the `molniya` example again?

If this doesn't solve the issue, please let us know here.

Thanks!!
