### ISSUE TITLE
Unable to install due to problems with llvmlite

### ISSUE THREAD

**Issue by konsbn** [poliastro/poliastro#141]
I have been trying to install this package for quite a while now and even after doing much tweaking I am unable to do so 
the following error always pops up
```
Failed building wheel for llvmlite
Command "/usr/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-f1b_8t9f/llvmlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-e7a32q19-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-f1b_8t9f/llvmlite/

```
# Please help me.
## Here is the complete log
```
Collecting poliastro
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python3.5/dist-packages (from poliastro)
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /usr/local/lib/python3.5/dist-packages (from poliastro)
Requirement already satisfied (use --upgrade to upgrade): scipy in /usr/local/lib/python3.5/dist-packages (from poliastro)
Collecting astropy>=1.0 (from poliastro)
  Using cached astropy-1.2.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting numba>=0.23 (from poliastro)
Collecting jplephem (from poliastro)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python3.5/dist-packages (from matplotlib->poliastro)
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/lib/python3.5/dist-packages (from matplotlib->poliastro)
Requirement already satisfied (use --upgrade to upgrade): cycler in /usr/local/lib/python3.5/dist-packages (from matplotlib->poliastro)
Requirement already satisfied (use --upgrade to upgrade): pyparsing!=2.0.0,!=2.0.4,!=2.1.2,>=1.5.6 in /usr/local/lib/python3.5/dist-packages (from matplotlib->poliastro)
Collecting llvmlite (from numba>=0.23->poliastro)
  Using cached llvmlite-0.14.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/local/lib/python3.5/dist-packages (from python-dateutil->matplotlib->poliastro)
Building wheels for collected packages: llvmlite
  Running setup.py bdist_wheel for llvmlite: started
  Running setup.py bdist_wheel for llvmlite: finished with status 'error'
  Complete output from command /usr/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-f1b_8t9f/llvmlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp8ozq6ocwpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  got version from file /tmp/pip-build-f1b_8t9f/llvmlite/llvmlite/_version.py {'full': '2dad935106b4ad224d9175ccefe8e265ef6be6b8', 'version': '0.14.0'}
  running build_ext
  /usr/bin/python3.5 /tmp/pip-build-f1b_8t9f/llvmlite/ffi/build.py
  LLVM version... 3.4
  
  Traceback (most recent call last):
    File "/tmp/pip-build-f1b_8t9f/llvmlite/ffi/build.py", line 152, in <module>
      main()
    File "/tmp/pip-build-f1b_8t9f/llvmlite/ffi/build.py", line 142, in main
      main_posix('linux', '.so')
    File "/tmp/pip-build-f1b_8t9f/llvmlite/ffi/build.py", line 119, in main_posix
      raise RuntimeError(msg)
  RuntimeError: Building llvmlite requires LLVM 3.8.x. Be sure to set LLVM_CONFIG to the right executable path.
  Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
  
  error: command '/usr/bin/python3.5' failed with exit status 1
  
  ----------------------------------------
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: astropy, llvmlite, numba, jplephem, poliastro
  Running setup.py install for llvmlite: started
    Running setup.py install for llvmlite: finished with status 'error'
    Complete output from command /usr/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-f1b_8t9f/llvmlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-e7a32q19-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    got version from file /tmp/pip-build-f1b_8t9f/llvmlite/llvmlite/_version.py {'full': '2dad935106b4ad224d9175ccefe8e265ef6be6b8', 'version': '0.14.0'}
    running build_ext
    /usr/bin/python3.5 /tmp/pip-build-f1b_8t9f/llvmlite/ffi/build.py
    LLVM version... 3.4
    
    Traceback (most recent call last):
      File "/tmp/pip-build-f1b_8t9f/llvmlite/ffi/build.py", line 152, in <module>
        main()
      File "/tmp/pip-build-f1b_8t9f/llvmlite/ffi/build.py", line 142, in main
        main_posix('linux', '.so')
      File "/tmp/pip-build-f1b_8t9f/llvmlite/ffi/build.py", line 119, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 3.8.x. Be sure to set LLVM_CONFIG to the right executable path.
    Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
    
    error: command '/usr/bin/python3.5' failed with exit status 1
    
```

**Comment by Juanlu001** [comment]
Hi @konsbn, thanks for reporting an issue! The problem you're seeing is because of numba and llvmlite. In principle it's possible to install llvmlite it using pip following [these instructions](http://llvmlite.readthedocs.io/en/stable/install/index.html#building-manually).

However, I can't support you when installing it because you'd better use [the numba-users mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/numba-users).

Instead, I recommend you either one of two things:

* Install all the requirements except numba, and then poliastro without dependencies:

```
$ pip install astropy jplephem
$ pip install --no-deps poliastro
```

(I should actually provide an easier way to do this)

* Use conda:

```
$ conda create --name py35 python=3.5 poliastro --channel conda-forge
$ source activate py35
(py35) $ python -c "import poliastro; print(poliastro.__version__)"
0.5.0
```

I'm closing this issue because I understand that you will be able to install poliastro using one of the two methods suggested above, but feel free to comment if you still have problems.

**Comment by eric-wieser** [comment]
Passing `--prefer-binary` to `pip` might help prevent it compiling an old version

**Comment by erush91** [comment]
> Passing `--prefer-binary` to `pip` might help prevent it trying to compile `llvmlite` itself

This resolved a related issue I was having. I couldn't install "pip install torch-geometric" (https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html) and was getting this error:
![llvmlite_error](https://user-images.githubusercontent.com/33467025/84085757-48465e00-a9b4-11ea-8c4e-32aa08b2ee0a.png)
