### ISSUE TITLE
`ValueError` when using passing `Time` objects to `build_ephem_interpolant`

### ISSUE THREAD

**Issue by Nosudrum** [poliastro/poliastro#1504]
🐞 **Problem**

I have start and end epochs defined as `<Time object: scale='utc' format='datetime' value=2020-01-01 00:00:00>` and `<Time object: scale='utc' format='datetime' value=2020-01-31 00:00:00>`, and when they are used in the `build_ephem_interpolant` function I get the following error :
```
Traceback (most recent call last):
  File "C:\Users\a.muller\Anaconda3\envs\poliastro\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\a.muller\Anaconda3\envs\poliastro\lib\site-packages\poliastro\ephem.py", line 56, in build_ephem_interpolant
    t_span = (t_span[0].to_value(u.d), t_span[1].to_value(u.d) + 0.01)
  File "C:\Users\a.muller\Anaconda3\envs\poliastro\lib\site-packages\astropy\time\core.py", line 768, in to_value
    raise ValueError(f'format must be one of {list(self.FORMATS)}')
ValueError: format must be one of ['jd', 'mjd', 'decimalyear', 'unix', 'unix_tai', 'cxcsec', 'gps', 'plot_date', 'stardate', 'datetime', 'ymdhms', 'iso', 'isot', 'yday', 'datetime64', 'fits', 'byear', 'jyear', 'byear_str', 'jyear_str']
```
After testing in the console, it appears that calling `.to_value(u.d)` on my epochs causes this error and throws the same message :
```
Traceback (most recent call last):
  File "C:\Users\a.muller\Anaconda3\envs\poliastro\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\a.muller\Anaconda3\envs\poliastro\lib\site-packages\astropy\time\core.py", line 768, in to_value
    raise ValueError(f'format must be one of {list(self.FORMATS)}')
ValueError: format must be one of ['jd', 'mjd', 'decimalyear', 'unix', 'unix_tai', 'cxcsec', 'gps', 'plot_date', 'stardate', 'datetime', 'ymdhms', 'iso', 'isot', 'yday', 'datetime64', 'fits', 'byear', 'jyear', 'byear_str', 'jyear_str']
```
So even though the epochs I am using are formatted in `datetime`, which is listed  as a compatible format, and work just fine in the propagation, this function that needs `to_value(u.d)` does not work.

You might be able to reproduce the issue on your end simply with the following commands :
```
from datetime import datetime
from astropy import units as u
from astropy.time import Time

Time(datetime.now()).to_value(u.d)
```

🖥 **Please paste the output of following commands**

* `conda info -a` (only if you have conda)
```bash
     active environment : poliastro
    active env location : C:\Users\a.muller\Anaconda3\envs\poliastro
            shell level : 2
       user config file : C:\Users\a.muller\.condarc
 populated config files : C:\Users\a.muller\.condarc
          conda version : 4.12.0
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.3=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\a.muller\Anaconda3  (writable)
      conda av data dir : C:\Users\a.muller\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/tudat-team/win-64
                          https://conda.anaconda.org/tudat-team/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\a.muller\Anaconda3\pkgs
                          C:\Users\a.muller\.conda\pkgs
                          C:\Users\a.muller\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\a.muller\Anaconda3\envs
                          C:\Users\a.muller\.conda\envs
                          C:\Users\a.muller\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

# conda environments:
#
base                     C:\Users\a.muller\Anaconda3
orekit-python            C:\Users\a.muller\Anaconda3\envs\orekit-python
poliastro             *  C:\Users\a.muller\Anaconda3\envs\poliastro
tudat-space              C:\Users\a.muller\Anaconda3\envs\tudat-space

sys.version: 3.9.7 (default, Sep 16 2021, 16:59:28) [...
sys.prefix: C:\Users\a.muller\Anaconda3
sys.executable: C:\Users\a.muller\Anaconda3\python.exe
conda location: C:\Users\a.muller\Anaconda3\lib\site-packages\conda
conda-build: C:\Users\a.muller\Anaconda3\Scripts\conda-build.exe
conda-content-trust: C:\Users\a.muller\Anaconda3\Scripts\conda-content-trust.exe
conda-convert: C:\Users\a.muller\Anaconda3\Scripts\conda-convert.exe
conda-debug: C:\Users\a.muller\Anaconda3\Scripts\conda-debug.exe
conda-develop: C:\Users\a.muller\Anaconda3\Scripts\conda-develop.exe
conda-env: C:\Users\a.muller\Anaconda3\Scripts\conda-env.exe
conda-index: C:\Users\a.muller\Anaconda3\Scripts\conda-index.exe
conda-inspect: C:\Users\a.muller\Anaconda3\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\a.muller\Anaconda3\Scripts\conda-metapackage.exe
conda-pack: C:\Users\a.muller\Anaconda3\Scripts\conda-pack.exe
conda-render: C:\Users\a.muller\Anaconda3\Scripts\conda-render.exe
conda-repo: C:\Users\a.muller\Anaconda3\Scripts\conda-repo.exe
conda-server: C:\Users\a.muller\Anaconda3\Scripts\conda-server.exe
conda-skeleton: C:\Users\a.muller\Anaconda3\Scripts\conda-skeleton.exe
conda-token: C:\Users\a.muller\Anaconda3\Scripts\conda-token.exe
conda-verify: C:\Users\a.muller\Anaconda3\Scripts\conda-verify.exe
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: poliastro
CONDA_EXE: C:\Users\a.muller\Anaconda3\Scripts\conda.exe
CONDA_PREFIX: C:\Users\a.muller\Anaconda3\envs\poliastro
CONDA_PREFIX_1: C:\Users\a.muller\Anaconda3
CONDA_PROMPT_MODIFIER: (poliastro)
CONDA_PYTHON_EXE: C:\Users\a.muller\Anaconda3\python.exe
CONDA_ROOT: C:\Users\a.muller\Anaconda3
CONDA_SHLVL: 2
CURL_CA_BUNDLE: <not set>
HOMEPATH: \
PATH: C:\Users\a.muller\Anaconda3;C:\Users\a.muller\Anaconda3\Library\mingw-w64\bin;C:\Users\a.muller\Anaconda3\Library\usr\bin;C:\Users\a.muller\Anaconda3\Library\bin;C:\Users\a.muller\Anaconda3\Scripts;C:\Users\a.muller\Anaconda3\bin;C:\Users\a.muller\Anaconda3\envs\poliastro;C:\Users\a.muller\Anaconda3\envs\poliastro\Library\mingw-w64\bin;C:\Users\a.muller\Anaconda3\envs\poliastro\Library\usr\bin;C:\Users\a.muller\Anaconda3\envs\poliastro\Library\bin;C:\Users\a.muller\Anaconda3\envs\poliastro\Scripts;C:\Users\a.muller\Anaconda3\envs\poliastro\bin;C:\Users\a.muller\Anaconda3\condabin;C:\Python365\Scripts;C:\Python365;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\System32\OpenSSH;C:\Users\a.muller\AppData\Local\Microsoft\WindowsApps;C:\Users\a.muller\AppData\Local\JetBrains\PyCharm 2022.1\bin;.;C:\Users\a.muller\AppData\Local\Programs\Git\cmd;C:\Users\a.muller\AppData\Local\GitHubDesktop\bin
PSMODULEPATH: D:\a.muller\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
```
* `conda list` (only if you have conda)
```bash
# packages in environment at C:\Users\a.muller\Anaconda3\envs\poliastro:
#
# Name                    Version                   Build  Channel
astropy                   4.3.1            py39hc7d831d_0
astroquery                0.4.6              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2021.10.8        py39hcbf5309_2    conda-forge
cffi                      1.15.0           py39h0878f49_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
cryptography              36.0.2           py39h7bc7c5c_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
czml3                     0.7.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.33.3           py39hb82d6ee_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
icu                       69.1                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py39hcbf5309_1    conda-forge
importlib_metadata        4.11.3               hd8ed1ab_1    conda-forge
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jpeg                      9e                   h8ffe710_1    conda-forge
jplephem                  2.17               pyhf3f802f_0    conda-forge
keyring                   23.4.0           py39hcbf5309_2    conda-forge
kiwisolver                1.4.2            py39h2e07f2f_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              14_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              14_win64_mkl    conda-forge
libclang                  13.0.1          default_h81446c8_0    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
liblapack                 3.9.0              14_win64_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libtiff                   4.3.0                hc4061b1_3    conda-forge
libwebp                   1.2.2                h57928b3_0    conda-forge
libwebp-base              1.2.2                h8ffe710_1    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libzlib                   1.2.11            h8ffe710_1014    conda-forge
llvmlite                  0.38.0           py39ha0cd8c8_1    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib                3.5.2            py39hcbf5309_0    conda-forge
matplotlib-base           3.5.2            py39h581301d_0    conda-forge
mkl                       2022.0.0           h0e2418a_796    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
numba                     0.55.1           py39hb8cd55e_0    conda-forge
numpy                     1.21.6           py39h6331f09_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1o               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pillow                    9.1.0            py39ha53f419_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
plotly                    5.7.0              pyhd8ed1ab_0    conda-forge
poliastro                 0.16.3             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyerfa                    2.0.0.1          py39h5d4886f_2    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39hcbf5309_8    conda-forge
pyqt-impl                 5.12.3           py39h415ef7b_8    conda-forge
pyqt5-sip                 4.19.18          py39h415ef7b_8    conda-forge
pyqtchart                 5.12             py39h415ef7b_8    conda-forge
pyqtwebengine             5.12.1           py39h415ef7b_8    conda-forge
pysocks                   1.7.1            py39hcbf5309_5    conda-forge
python                    3.9.12          h9a09f29_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pyvo                      1.3                pyhd8ed1ab_0    conda-forge
pywin32-ctypes            0.2.0           py39hcbf5309_1005    conda-forge
pyyaml                    6.0              py39hb82d6ee_4    conda-forge
qt                        5.12.9               h556501e_6    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
scipy                     1.8.0            py39hc0c34ad_1    conda-forge
setuptools                62.1.0           py39hcbf5309_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.38.5               h8ffe710_0    conda-forge
tbb                       2021.5.0             h2d74725_1    conda-forge
tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tornado                   6.1              py39hb82d6ee_3    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py39hb82d6ee_1    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
w3lib                     1.22.0             pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_4    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h8ffe710_1014    conda-forge
zstd                      1.5.2                h6255e5f_0    conda-forge
```

* `pip freeze`
```bash
astropy @ file:///C:/ci/astropy_1629829318700/work
astroquery==0.4.6
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1640799537051/work
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1649463573192/work
brotlipy @ file:///D:/bld/brotlipy_1648854327487/work
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
certifi==2021.10.8
cffi @ file:///D:/bld/cffi_1636046278333/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1644853463426/work
cryptography @ file:///D:/bld/cryptography_1649035434655/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
czml3 @ file:///home/conda/feedstock_root/build_artifacts/czml3_1639548540228/work
fonttools @ file:///D:/bld/fonttools_1651018206941/work
html5lib @ file:///home/conda/feedstock_root/build_artifacts/html5lib_1592930327044/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1642433548627/work
importlib-metadata @ file:///D:/bld/importlib-metadata_1648728550588/work
jplephem @ file:///home/conda/feedstock_root/build_artifacts/jplephem_1640954253146/work
keyring @ file:///D:/bld/keyring_1643122234718/work
kiwisolver @ file:///D:/bld/kiwisolver_1648854553193/work
llvmlite==0.38.0
matplotlib @ file:///D:/bld/matplotlib-suite_1651609646819/work
munkres==1.1.4
numba @ file:///D:/bld/numba_1644004406986/work
numpy @ file:///D:/bld/numpy_1649806531213/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1637239678211/work
Pillow @ file:///D:/bld/pillow_1649818211002/work
plotly @ file:///home/conda/feedstock_root/build_artifacts/plotly_1649183764952/work
poliastro @ file:///home/conda/feedstock_root/build_artifacts/poliastro_1652129457343/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pyerfa @ file:///D:/bld/pyerfa_1649586279666/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1643496850550/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1649603503565/work
PyQt5==5.12.3
PyQt5_sip==4.19.18
PyQtChart==5.12
PyQtWebEngine==5.12.1
PySocks @ file:///D:/bld/pysocks_1648857426942/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pyvo @ file:///home/conda/feedstock_root/build_artifacts/pyvo_1645470589834/work
pywin32-ctypes @ file:///D:/bld/pywin32-ctypes_1648607901171/work
PyYAML @ file:///D:/bld/pyyaml_1648757346451/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1641580202195/work
scipy @ file:///C:/bld/scipy_1644357595180/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1638550740809/work
tenacity @ file:///home/conda/feedstock_root/build_artifacts/tenacity_1626090218611/work
tornado @ file:///D:/bld/tornado_1648827405403/work
unicodedata2 @ file:///D:/bld/unicodedata2_1649112114189/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1647489083693/work
w3lib @ file:///home/conda/feedstock_root/build_artifacts/w3lib_1591173357158/work
webencodings==0.5.1
win-inet-pton @ file:///D:/bld/win_inet_pton_1648771910527/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1649012893348/work
```

</details>

**Comment by Nosudrum** [comment]
Hi @astrojuanlu, thanks for your answer.

I saw the examples you linked when writing my code, but when calling `build_ephem_interpolant` after doing `.value` on my datetime-formatted `Time` objects I get the following error :
```
AttributeError: 'datetime.datetime' object has no attribute 'to_value'
```
This initially lead me to believe that `build_ephem_interpolant` expects Time objects to be able to call `.to_value()` in the following line : 
```
t_span = (t_span[0].to_value(u.d), t_span[1].to_value(u.d) + 0.01)
```
However, you said this is not the case and it expects `Quantity` objects.
Therefore, I suppose that when I do `epoch.value` and get `datetime.datetime(2020, 1, 1, 0, 0)`, it is actually not a `Quantity` object ?

Any idea how to circumvent this issue ?

**Comment by astrojuanlu** [comment]
First of all, what's really confusing here is that there are two identically named `to_value` methods that do totally different things:

- [`Quantity.to_value`](https://docs.astropy.org/en/latest/api/astropy.units.Quantity.html#astropy.units.Quantity.to_value) returns the raw value of a `Quantity` in a given unit:

```
In [10]: jdate = 2454283.0 * u.day

In [11]: jdate
Out[11]: <Quantity 2454283. d>

In [12]: jdate.to_value(u.s)
Out[12]: 212050051200.0
```

- [`Time.to_value`](https://docs.astropy.org/en/latest/api/astropy.time.Time.html#astropy.time.Time.to_value) returns the time values in a given format:

```
In [13]: tjdate = Time(jdate, format="jd")

In [14]: tjdate
Out[14]: <Time object: scale='utc' format='jd' value=2454283.0>

In [15]: tjdate.to_value("mjd")
Out[15]: 54282.5
```

I think this explains the first surprising error message you found.

About the second one, indeed `.value` does not do what you need to call `build_ephem_interpolant`: you'd need to convert those `Time` objects you created from `datetime` to a `Quantity`, which is in fact the Julian Date (i.e. elapsed time from a reference epoch). For that, you need `Time.to_value` precisely! Something like this:

```
In [17]: tdt = Time(dt.datetime.now())

In [18]: tdt
Out[18]: <Time object: scale='utc' format='datetime' value=2022-05-17 20:16:42.580459>

In [19]: tdt.value
Out[19]: datetime.datetime(2022, 5, 17, 20, 16, 42, 580459)

In [20]: tdt.to_value("jd")  # No units!
Out[20]: 2459717.3449372738

In [21]: tdt.to_value("jd") << u.d  # This is fine
Out[21]: <Quantity 2459717.34493727 d>

In [22]: Time(tdt.to_value("jd") << u.d, format="jd")  # Verify that the roundtrip works
Out[22]: <Time object: scale='utc' format='jd' value=2459717.3449372738>

In [23]: _.isot
Out[23]: '2022-05-17T20:16:42.580'
```

Please let me know if this helps.

**Comment by Nosudrum** [comment]
Ah yes that works perfectly, thanks a lot !

One last question, on the subject of `build_ephem_interpolant` : [the documentation](https://docs.poliastro.space/en/stable/autoapi/poliastro/ephem/index.html#poliastro.ephem.build_ephem_interpolant) simply says that the second parameter to pass is the `Orbital period` of the body, with no further explanation on its use in the function.

But what if I am trying to setup 3rd body perturbation of the Sun in an Earth-centered propagation ?
Do I set the orbital period of the sun to 1 year ? (just saying this makes me shiver haha)

Thank you for your help :)

**Comment by Nosudrum** [comment]
Alright thanks !

And now I'm encountering two new errors with my two lines of `build_ephem_interpolant`.
I'm commenting in this issue still to avoid spamming with issues, but do let me know if you'd rather me proceed differently !

Here are my two lines of code :
```
Sun_r = build_ephem_interpolant(Sun, 1 * u.year, (epoch_start.to_value("jd") << u.d, epoch_end.to_value("jd") << u.d), rtol=1e-2)
Moon_r = build_ephem_interpolant(Moon, 28 * u.day, (epoch_start.to_value("jd") << u.d, epoch_end.to_value("jd") << u.d), rtol=1e-2)
```
where `(epoch_start.to_value("jd") << u.d, epoch_end.to_value("jd") << u.d)` is `(<Quantity 2458849.5 d>, <Quantity 2458850.5 d>)`.

This first line, with `Sun`, results in
```
Traceback (most recent call last):
  File "C:\Users\a.muller\Anaconda3\envs\poliastro\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\a.muller\Anaconda3\envs\poliastro\lib\site-packages\poliastro\ephem.py", line 78, in build_ephem_interpolant
    return interp1d(
  File "C:\Users\a.muller\Anaconda3\envs\poliastro\lib\site-packages\scipy\interpolate\_interpolate.py", line 484, in __init__
    self._y = self._reshape_yi(self.y)
  File "C:\Users\a.muller\Anaconda3\envs\poliastro\lib\site-packages\scipy\interpolate\_polyint.py", line 110, in _reshape_yi
    return yi.reshape((yi.shape[0], -1))
ValueError: cannot reshape array of size 0 into shape (0,newaxis)
```
while the second one, with `Moon`, results in
```
Traceback (most recent call last):
  File "C:\Users\a.muller\Anaconda3\envs\poliastro\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\a.muller\Anaconda3\envs\poliastro\lib\site-packages\poliastro\ephem.py", line 78, in build_ephem_interpolant
    return interp1d(
  File "C:\Users\a.muller\Anaconda3\envs\poliastro\lib\site-packages\scipy\interpolate\_interpolate.py", line 564, in __init__
    self._spline = make_interp_spline(xx, yy, k=order,
  File "C:\Users\a.muller\Anaconda3\envs\poliastro\lib\site-packages\scipy\interpolate\_bsplines.py", line 1326, in make_interp_spline
    raise ValueError("The number of derivatives at boundaries does not "
ValueError: The number of derivatives at boundaries does not match: expected 1, got 0+0
```

Any ideas ? 

Thanks a lot :)

**Comment by Nosudrum** [comment]
I see, thanks. Indeed `build_ephem_interpolant` works fine with longer propagation durations (tried 30 days).

Since my code uses propagation start & end epochs as input, which can be anywhere from minutes to months apart, I would rather try using your `main` branch with the `ephem.py` improvements.

After setting things up, I now get the following error (with the same code as above) :
```
Traceback (most recent call last):
  File "C:\Users\a.muller\Anaconda3\envs\poliastro-main\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\a.muller\AppData\Local\JetBrains\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\a.muller\AppData\Local\JetBrains\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/a.muller/Documents/GitHub/2022_muller_arnaud/poliastro-main/allModels.py", line 71, in <module>
    Sun_r = build_ephem_interpolant(Sun, 1 * u.year, (epoch_start.to_value("jd") << u.d, epoch_end.to_value("jd") << u.d),
  File "C:\Users\a.muller\Anaconda3\envs\poliastro-main\lib\site-packages\poliastro\ephem.py", line 56, in build_ephem_interpolant
    ephem = Ephem.from_body(body, epochs, attractor=attractor)
  File "C:\Users\a.muller\Anaconda3\envs\poliastro-main\lib\site-packages\poliastro\ephem.py", line 228, in from_body
    ICRS(coordinates)
  File "C:\Users\a.muller\Anaconda3\envs\poliastro-main\lib\site-packages\astropy\coordinates\baseframe.py", line 1045, in represent_as
    raise TypeError('Frame data has no associated differentials '
TypeError: Frame data has no associated differentials (i.e. the frame has no velocity data) - represent_as() only accepts a new representation.
```
I'm guessing this has to do with a change in the input parameters, correct ? What arguments types am I now expected to pass to `build_ephem_interpolant` ?

Also, I'm not sure if this qualifies for a new issue relevant to the `main` branch or not. Let me know how you prefer to handle this.

Again, thanks a lot for your help ! :)

**Comment by astrojuanlu** [comment]
This one I have no idea where does it come from. There are 2 different issues here:

- `ValueError` when interpolating on a narrow window
- `TypeError` when trying to build an ephem interpolant for the `Sun`

If you could open them with reproducers, that would help us a lot dig a bit deeper. When that is done, we can close this one.

Thanks for your patience and cooperation!
