### ISSUE TITLE
poliastro.plotting seems broken by numpy and numba version incompatibilities 

### ISSUE THREAD

**Issue by earthshrink** [poliastro/poliastro#1572]
Executing
```
from poliastro.plotting.misc import plot_solar_system
```
produces
```
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/astro/.local/lib/python3.10/site-packages/poliastro/plotting/__init__.py", line 2, in <module>
    from poliastro.plotting.static import StaticOrbitPlotter
  File "/home/astro/.local/lib/python3.10/site-packages/poliastro/plotting/static.py", line 3, in <module>
    from matplotlib import patches as mpl_patches, pyplot as plt
  File "/usr/lib/python3.10/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/usr/lib/python3.10/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/usr/lib/python3.10/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/usr/lib/python3.10/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/usr/lib/python3.10/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/usr/lib/python3.10/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import
```
I have the following installed:
```
$ pip freeze | fgrep -e numpy -e poliastro
numpy==1.22.4
poliastro==0.17.0
```
So I upgrade `numpy`
```
$ pip install --user numpy --upgrade
Requirement already satisfied: numpy in ./.local/lib/python3.10/site-packages (1.22.4)
Collecting numpy
  Downloading numpy-1.23.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 74.1 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
  WARNING: The scripts f2py, f2py3 and f2py3.10 are installed in '/home/astro/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.0 requires numpy<1.23,>=1.18, but you have numpy 1.23.2 which is incompatible.
Successfully installed numpy-1.23.2
```
So now of course `numba` is not happy:
```
$ python -q
>>> from poliastro.ephem import Ephem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/astro/.local/lib/python3.10/site-packages/poliastro/ephem.py", line 17, in <module>
    from poliastro.frames.util import get_frame
  File "/home/astro/.local/lib/python3.10/site-packages/poliastro/frames/util.py", line 35, in <module>
    from poliastro.frames.fixed import (
  File "/home/astro/.local/lib/python3.10/site-packages/poliastro/frames/fixed.py", line 25, in <module>
    from poliastro.core.fixed import (
  File "/home/astro/.local/lib/python3.10/site-packages/poliastro/core/fixed.py", line 19, in <module>
    from numba import njit as jit
  File "/home/astro/.local/lib/python3.10/site-packages/numba/__init__.py", line 206, in <module>
    _ensure_critical_deps()
  File "/home/astro/.local/lib/python3.10/site-packages/numba/__init__.py", line 146, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.22 or less")
ImportError: Numba needs NumPy 1.22 or less
>>> 
```
I already tried regressing `poliastro` to 0.16 but could not get past this issue.
I must be doing something stupid, since 0.17 has been presented successfully, presumably with the plots. Would greatly appreciate any pointers to get the plotting going.

**Comment by astrojuanlu** [comment]
Hi @earthshrink, thanks for your interest in poliastro!

I tried a clean installation in a Docker image and it worked.

<details>
```
$ docker run -it --rm python:3.10 bash
root@d9cdb67d943f:/# python3 -m venv .venv
root@d9cdb67d943f:/# source .venv/bin/activate
(.venv) root@d9cdb67d943f:/# pip install -U pip &> /dev/null 
(.venv) root@d9cdb67d943f:/# pip --version
pip 22.2.2 from /.venv/lib/python3.10/site-packages/pip (python 3.10)
(.venv) root@d9cdb67d943f:/# pip install poliastro
Collecting poliastro
  Downloading poliastro-0.17.0-py3-none-any.whl (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.7/162.7 kB 3.7 MB/s eta 0:00:00
Collecting numba>=0.53.0
  Downloading numba-0.56.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 4.9 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-1.23.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 8.1 MB/s eta 0:00:00
Collecting pandas
  Downloading pandas-1.4.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 8.1 MB/s eta 0:00:00
Collecting plotly<6,>=4.0
  Downloading plotly-5.10.0-py2.py3-none-any.whl (15.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 7.8 MB/s eta 0:00:00
Collecting astropy<6,>=5.0
  Downloading astropy-5.1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (10.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 7.1 MB/s eta 0:00:00
Collecting pyerfa
  Downloading pyerfa-2.0.0.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (743 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 743.2/743.2 kB 6.5 MB/s eta 0:00:00
Collecting jplephem
  Downloading jplephem-2.17-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.3/46.3 kB 8.0 MB/s eta 0:00:00
Collecting scipy>=1.4.0
  Downloading scipy-1.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.9/43.9 MB 8.0 MB/s eta 0:00:00
Collecting astroquery>=0.3.9
  Downloading astroquery-0.4.6-py3-none-any.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 7.1 MB/s eta 0:00:00
Collecting matplotlib!=3.0.1,>=2.0
  Downloading matplotlib-3.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 7.4 MB/s eta 0:00:00
Collecting PyYAML>=3.13
  Downloading PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.2/682.2 kB 7.6 MB/s eta 0:00:00
Collecting packaging>=19.0
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 7.2 MB/s eta 0:00:00
Collecting beautifulsoup4>=4.3.2
  Downloading beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 kB 2.9 MB/s eta 0:00:00
Collecting keyring>=4.0
  Downloading keyring-23.8.2-py3-none-any.whl (34 kB)
Collecting html5lib>=0.999
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 9.4 MB/s eta 0:00:00
Collecting pyvo>=1.1
  Downloading pyvo-1.3-py3-none-any.whl (829 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.6/829.6 kB 7.7 MB/s eta 0:00:00
Collecting requests>=2.4.3
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 5.7 MB/s eta 0:00:00
Collecting pillow>=6.2.0
  Downloading Pillow-9.2.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 7.7 MB/s eta 0:00:00
Collecting pyparsing>=2.2.1
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 5.9 MB/s eta 0:00:00
Collecting python-dateutil>=2.7
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 8.2 MB/s eta 0:00:00
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 8.0 MB/s eta 0:00:00
Collecting fonttools>=4.22.0
  Downloading fonttools-4.37.0-py3-none-any.whl (956 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 956.5/956.5 kB 7.2 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-1.22.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 8.4 MB/s eta 0:00:00
Collecting llvmlite<0.40,>=0.39.0dev0
  Downloading llvmlite-0.39.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.6/34.6 MB 7.9 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /.venv/lib/python3.10/site-packages (from numba>=0.53.0->poliastro) (63.2.0)
Collecting tenacity>=6.2.0
  Downloading tenacity-8.0.1-py3-none-any.whl (24 kB)
Collecting pytz>=2020.1
  Downloading pytz-2022.2.1-py2.py3-none-any.whl (500 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 500.6/500.6 kB 8.5 MB/s eta 0:00:00
Collecting soupsieve>1.2
  Downloading soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting six>=1.9
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting SecretStorage>=3.2
  Downloading SecretStorage-3.3.3-py3-none-any.whl (15 kB)
Collecting jeepney>=0.4.2
  Downloading jeepney-0.8.0-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 9.3 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 4.9 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 kB 9.7 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.6.15-py3-none-any.whl (160 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.2/160.2 kB 9.3 MB/s eta 0:00:00
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting cryptography>=2.0
  Downloading cryptography-37.0.4-cp36-abi3-manylinux_2_24_x86_64.whl (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 7.9 MB/s eta 0:00:00
Collecting cffi>=1.12
  Downloading cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.8/441.8 kB 5.9 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 1.5 MB/s eta 0:00:00
Installing collected packages: webencodings, pytz, urllib3, tenacity, soupsieve, six, PyYAML, pyparsing, pycparser, pillow, numpy, llvmlite, kiwisolver, jeepney, idna, fonttools, cycler, charset-normalizer, certifi, scipy, requests, python-dateutil, pyerfa, plotly, packaging, numba, jplephem, html5lib, cffi, beautifulsoup4, pandas, matplotlib, cryptography, astropy, SecretStorage, pyvo, keyring, astroquery, poliastro
Successfully installed PyYAML-6.0 SecretStorage-3.3.3 astropy-5.1 astroquery-0.4.6 beautifulsoup4-4.11.1 certifi-2022.6.15 cffi-1.15.1 charset-normalizer-2.1.1 cryptography-37.0.4 cycler-0.11.0 fonttools-4.37.0 html5lib-1.1 idna-3.3 jeepney-0.8.0 jplephem-2.17 keyring-23.8.2 kiwisolver-1.4.4 llvmlite-0.39.0 matplotlib-3.5.3 numba-0.56.0 numpy-1.22.4 packaging-21.3 pandas-1.4.3 pillow-9.2.0 plotly-5.10.0 poliastro-0.17.0 pycparser-2.21 pyerfa-2.0.0.1 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.2.1 pyvo-1.3 requests-2.28.1 scipy-1.9.0 six-1.16.0 soupsieve-2.3.2.post1 tenacity-8.0.1 urllib3-1.26.12 webencodings-0.5.1
(.venv) root@d9cdb67d943f:/# python -q
>>> from poliastro.plotting.misc import plot_solar_system
>>> from poliastro.ephem import Ephem
>>> 
(.venv) root@d9cdb67d943f:/# 
```
</details>

I think you have several problems:

- There's a mess with your Python installation: your first traceback shows a mix of `~/.local` packages and `/usr/lib/python3.10/` packages. I see from your pip commands that you're using `--user`. Consider creating a virtual environment instead.
- `pip install --upgrade numpy` does not take into account the constraints of the installed packages. I can reproduce this behavior:

```
(.venv) root@d9cdb67d943f:/# pip install -U numpy
Requirement already satisfied: numpy in /.venv/lib/python3.10/site-packages (1.22.4)
Collecting numpy
  Using cached numpy-1.23.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.0 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.0 requires numpy<1.23,>=1.18, but you have numpy 1.23.2 which is incompatible.
Successfully installed numpy-1.23.2
(.venv) root@d9cdb67d943f:/# pip check
numba 0.56.0 has requirement numpy<1.23,>=1.18, but you have numpy 1.23.2.
```

Upgrading both numba and numpy at the same time fixes the dependency issue:

```
(.venv) root@d9cdb67d943f:/# pip install -U numpy numba
Requirement already satisfied: numpy in /.venv/lib/python3.10/site-packages (1.23.2)
Requirement already satisfied: numba in /.venv/lib/python3.10/site-packages (0.56.0)
Requirement already satisfied: setuptools in /.venv/lib/python3.10/site-packages (from numba) (63.2.0)
Collecting numpy
  Using cached numpy-1.22.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in /.venv/lib/python3.10/site-packages (from numba) (0.39.0)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.2
    Uninstalling numpy-1.23.2:
      Successfully uninstalled numpy-1.23.2
Successfully installed numpy-1.22.4
(.venv) root@d9cdb67d943f:/# pip check
No broken requirements found.
```

You found typical problems with Python packaging, [whatever that means to you](https://gist.github.com/astrojuanlu/9a7419d3281d4689ae05df613e0bf9c0). Let me know if you manage to get a working poliastro installation.

**Comment by earthshrink** [comment]
I had got rid of conda and was avoiding venv because python's replication on disk across application domains was making me version-dizzy. (But guess it's now the cloud & space age and terra firma is a lost cause in every sense!)
Venv (with its duplication on disk) indeed solves the problem- I see 23 packages including `matplotlib` have a different version in the working venv. Thanks so much for looking into it, and apologies for taking your time.

**Comment by astrojuanlu** [comment]
Glad you solved it. While I'm not a fan of having the same version of my dependencies replicated a dozen times, I acknowledge that the current solution probably hits a good compromise between implementation complexity and cross-platform availability.

Maybe someone should make a venv that aggressively symlinks everything to reduce the replication factor to 1.0? 🙃 

And apart from this off-topic question, @earthshrink may I ask what are you considering using poliastro for?

**Comment by earthshrink** [comment]
Agreed. Re your further question, please see [github:earthshrink/flyby-analysis](https://github.com/earthshrink/flyby-analysis) and particularly the references given in About.md therein.

The anomalous residuals in the NEAR and Rosetta 2005 flyby residuals exhibit a pattern of excess light time delays in both Doppler, given by carrier frequency shift, and range, measured from round trip times of modulated PN codes. This pattern fits to 1%, and disagrees with known physics by well over 5σ, as shown by the graphs generated using JPL Horizons.

Further theoretical work (see snapshot at [techrxiv](https://www.techrxiv.org/articles/preprint/Parametric_separation_of_variables_and_the_complete_propagation_law/19620477)) makes it compelling to verify the reality of these delays in the range data. While Antreasian is investigating the original tracking data, it's interesting for me, as an ex-programmer, to see if I can at least reproduce the residuals:  starting with a realistic generated flyby trajectory, computing expected Doppler and range data with respect to a tracking station, faking the delays and verifying that a least squares trajectory computed from the resulting data would have similar anomalies. So far, I have found that `poliastro` is able to get me position and velocity vectors from Horizons for a close enough starting point, and can compute the incremental motion using JPL ephemerides. Hoping this will be fun!
