### ISSUE TITLE
AttributeError: gooding has no attribute 'kind'

### ISSUE THREAD

**Issue by X52p** [poliastro/poliastro#1578]
AttributeError when running '''.propagate''' with method "gooding"

running this code:
```python
from poliastro.twobody.propagation import propagate, gooding
from poliastro.twobody import Orbit
from poliastro.bodies import Earth
from astropy.time import Time
from astropy import units as u

EPOCH = Time("2022-01-01 12:00:00")

Orbit.from_classical(Earth, 50000 * u.km, 0.1 * u.one, 45 * u.deg, 0 * u.deg,
                     0 * u.deg, 0 * u.deg, epoch=EPOCH).propagate(10 * u.s, method=gooding)
```

results in this error message:
```python
Traceback (most recent call last):
  File "C:\Users\Kevin\ma\poliastrotest.py", line 9, in <module>
    Orbit.from_classical(Earth, 50000 * u.km, 0.1 * u.one, 45 * u.deg, 0 * u.deg,
  File "C:\Users\Kevin\ma\torch2Env\lib\site-packages\poliastro\twobody\orbit\scalar.py", line 431, in propagate
    if self.ecc < 1.0 and not (method.kind & PropagatorKind.ELLIPTIC):
AttributeError: module 'poliastro.twobody.propagation.gooding' has no attribute 'kind'
```

This code works when not using ```method=gooding```.

(selection of Kepler Elements is arbitrary and not relevant to the problem)

* `pip freeze`

<details>
  
```bash
# Paste your output here:
accel-brain-base==1.1.0
astropy==5.1
astroquery==0.4.6
attrs==22.1.0
beautifulsoup4==4.11.1
certifi==2022.6.15
charset-normalizer==2.1.1
cloudpickle==2.1.0
colorama==0.4.5
cycler==0.11.0
dill==0.3.5.1
docopt==0.6.2
fonttools==4.37.1
gitdb==4.0.9
GitPython==3.1.27
gym==0.21.0
html5lib==1.1
idna==3.3
importlib-metadata==4.12.0
iniconfig==1.1.1
jaraco.classes==3.2.2
joblib==1.1.0
jplephem==2.17
jsonpickle==1.5.2
keyring==23.9.1
kiwisolver==1.4.4
llvmlite==0.39.1
matplotlib==3.5.3
modAL==0.4.1
more-itertools==8.14.0
munch==2.5.0
numba==0.56.2
numpy==1.23.2
packaging==21.3
pandas==1.4.4
Pillow==9.2.0
plotly==5.10.0
pluggy==1.0.0
POAP==0.1.26
poliastro==0.17.0
py==1.11.0
py-cpuinfo==8.0.0
pyDOE2==1.3.0
pyerfa==2.0.0.1
pyglet==1.5.26
pyparsing==3.0.9
pySOT==0.3.3
pytest==7.1.3
python-dateutil==2.8.2
pytz==2022.2.1
pyvo==1.3
pywin32-ctypes==0.2.0
PyYAML==6.0
requests==2.28.1
sacred==0.8.2
scikit-learn==1.1.2
scipy==1.9.1
six==1.16.0
sklearn==0.0
smmap==5.0.0
sobol-seq==0.2.0
soupsieve==2.3.2.post1
stable-baselines3==1.6.0
surfer==0.0.1
tenacity==8.0.1
threadpoolctl==3.1.0
tomli==2.0.1
torch==1.12.1+cu113
torchaudio==0.12.1+cu113
torchvision==0.13.1+cu113
tqdm==4.64.1
typing-extensions==4.3.0
urllib3==1.26.12
webencodings==0.5.1
wrapt==1.14.1
zipp==3.8.1
```
</details>

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by astrojuanlu** [comment]
Hello @X52p, thanks for using poliastro!

Version 0.17.0 introduced some breaking changes in the propagator code. The reason why not specifying `method=gooding` works is because by default `method=FarnocchiaPropagator`.

To keep the code untouched, you will need to install 0.16.3.

**Comment by X52p** [comment]
OK, thank you.
Will the other Propagation methods be updated, or will they be removed later?

**Comment by astrojuanlu** [comment]
All the propagation methods have been updated but you have to change the code:

```python
from poliastro.twobody.propagation import GoodingPropagator

...
orbit.propagate(..., method=GoodingPropagator())
```

see https://docs.poliastro.space/en/stable/quickstart.html#studying-non-keplerian-orbits-perturbations for a similar example
