### ISSUE TITLE
Poliastro install fails on Python 3.11.2 ?

### ISSUE THREAD

**Issue by beluej123** [poliastro/poliastro#1620]
Poliastro install fails on Python 3.11.2 ?

python --version
Python 3.11.2
I do not have an earlier version of Python.

I just want to run some Poliastro examples to understand the scope of time commitment to get the Poliastro to run.
I plan on development thru VSCode ; I have a windows10 machine...

Yes, I realize the Poliastro install instruction;
"poliastro is supported on Linux, macOS and Windows on Python 3.8 to 3.10".  Is there a timeframe to test Poliastro for later versions of Python?

🐞 **Problem**

 python -m pip install https://github.com/poliastro/poliastro/archive/main.zip
 RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.

 python -m pip install https://github.com/poliastro/poliastro/archive/main.zip
Collecting https://github.com/poliastro/poliastro/archive/main.zip
  Using cached https://github.com/poliastro/poliastro/archive/main.zip
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting astropy<6,>=5.0
  Using cached astropy-5.2.1-cp311-cp311-win_amd64.whl (6.6 MB)
Collecting astroquery>=0.3.9
  Using cached astroquery-0.4.6-py3-none-any.whl (4.5 MB)
Collecting jplephem
  Using cached jplephem-2.18-py3-none-any.whl (46 kB)
Collecting matplotlib!=3.0.1,>=2.0
  Using cached matplotlib-3.7.1-cp311-cp311-win_amd64.whl (7.6 MB)
Collecting numba>=0.53.0
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [8 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\belue\AppData\Local\Temp\pip-install-wy42dzhv\numba_c517ce1077114a5b8c0bc686bbd8eb33\setup.py", line 51, in <module>
      _guard_py_ver()
    File "C:\Users\belue\AppData\Local\Temp\pip-install-wy42dzhv\numba_c517ce1077114a5b8c0bc686bbd8eb33\setup.py", line 48, in _guard_py_ver
      raise RuntimeError(msg.format(cur_py, min_py, max_py))
  RuntimeError: Cannot install on Python version 3.11.2; only versions >=3.7,<3.11 are supported.
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

```bash

Thank you for your help.
Jeff Belue

**Comment by daniellandau** [comment]
Situation is the same on Ubuntu Linux too, but the current main on GitHub does work, so one can `pip install git+https://github.com/poliastro/poliastro.git`

**Comment by astrojuanlu** [comment]
Fixed on the `main` branch 4 days ago :) https://github.com/poliastro/poliastro/pull/1590
