### ISSUE TITLE
Improve error messages in Python 2

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#298]
🐞 **Problem**

Many people try to install poliastro on Python 2 (see #297, #296) but it's unclear which version they are installing and why it fails. We have to:

* [ ] Improve the issue template to include `conda list`, poliastro version and proper formatting of the output (triple backquotes)
* [ ] If appropriate, release new micro versions from 0.4 and backwards that set proper upper bounds for dependencies and warn the user about compatibility

🎯 **Goal**

Improve the first run experience for newcomers, if their default Python installation is Python 2.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
Created a new issue for the template https://github.com/poliastro/poliastro/issues/355

**Comment by Juanlu001** [comment]
Another failed Python 2 installation: #384.

**Comment by Juanlu001** [comment]
I would like to do some testing on Windows and old Ubuntu versions with Python 2 before the next release so we can reduce the number of issues we get because of this thing.

**Comment by Juanlu001** [comment]
Another one #405, this time because the conda package was improperly generated. I will fix this once and for all.

**Comment by Juanlu001** [comment]
Fixing the conda package in https://github.com/conda-forge/poliastro-feedstock/pull/18, and asked in the Gitter chat how to fix older versions as well.

**Comment by Juanlu001** [comment]
Regarding the PyPI package, the problem seems to be poliastro 0.6.0. This happens in pip 9 and 10:

```
$ pip install poliastro
Collecting poliastro
  Downloading https://files.pythonhosted.org/packages/b2/19/12bfff8a233261ca60c2d347c3304cbb71cf1ffc51d8bbefe558fbd7e1ad/poliastro-0.6.0.tar.gz (968kB)
    100% |████████████████████████████████| 972kB 605kB/s 
poliastro requires Python '>=3.5' but the running Python is 2.7.15
```

**Comment by Juanlu001** [comment]
If one restricts the versions, the installation of 0.5.0 succeeds but there are some errors with numba:

```
$ python -c "import poliastro.testing; poliastro.testing.test()"
============================================= test session starts ==============================================
platform linux2 -- Python 2.7.15, pytest-3.6.3, py-1.5.4, pluggy-0.6.0
rootdir: /home/juanlu, inifile:
collected 24 items / 3 errors                                                                                  

==================================================== ERRORS ====================================================
____ ERROR collecting .miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/tests/test_ephem.py ____
ImportError while importing test module '/home/juanlu/.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/tests/test_ephem.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/tests/test_ephem.py:7: in <module>
    from poliastro import ephem
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/ephem.py:14: in <module>
    from urllib.request import urlretrieve
E   ImportError: No module named request
____ ERROR collecting .miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/tests/test_hyper.py ____
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/tests/test_hyper.py:7: in <module>
    from poliastro.hyper import hyp2f1b as hyp2f1
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/hyper.py:9: in <module>
    @jit('f8(f8)')
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/decorators.py:198: in wrapper
    disp.compile(sig)
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/dispatcher.py:653: in compile
    cres = self._compiler.compile(args, return_type)
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/dispatcher.py:83: in compile
    pipeline_class=self.pipeline_class)
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/compiler.py:873: in compile_extra
    return pipeline.compile_extra(func)
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/compiler.py:367: in compile_extra
    return self._compile_bytecode()
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/compiler.py:804: in _compile_bytecode
    return self._compile_core()
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/compiler.py:791: in _compile_core
    res = pm.run(self.status)
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/compiler.py:253: in run
    raise patched_exception
E   TypingError: Failed at nopython (nopython frontend)
E   No conversion from none to float64 for '$138.2', defined at None
E   
E   File "../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/hyper.py", line 26:
E   def hyp2f1b(x):
E       <source elided>
E                   return res
E               ii += 1
E               ^
E   
E   [1] During: typing of assignment at /home/juanlu/.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/hyper.py (26)
E   
E   File "../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/hyper.py", line 26:
E   def hyp2f1b(x):
E       <source elided>
E                   return res
E               ii += 1
E               ^
_____ ERROR collecting .miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/tests/test_iod.py _____
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/tests/test_iod.py:8: in <module>
    from poliastro.iod import izzo, vallado
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/iod/__init__.py:4: in <module>
    from poliastro.iod.izzo import lambert
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/iod/izzo.py:10: in <module>
    from poliastro.hyper import hyp2f1b
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/hyper.py:9: in <module>
    @jit('f8(f8)')
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/decorators.py:198: in wrapper
    disp.compile(sig)
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/dispatcher.py:653: in compile
    cres = self._compiler.compile(args, return_type)
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/dispatcher.py:83: in compile
    pipeline_class=self.pipeline_class)
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/compiler.py:873: in compile_extra
    return pipeline.compile_extra(func)
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/compiler.py:367: in compile_extra
    return self._compile_bytecode()
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/compiler.py:804: in _compile_bytecode
    return self._compile_core()
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/compiler.py:791: in _compile_core
    res = pm.run(self.status)
../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/numba/compiler.py:253: in run
    raise patched_exception
E   TypingError: Failed at nopython (nopython frontend)
E   No conversion from none to float64 for '$138.2', defined at None
E   
E   File "../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/hyper.py", line 26:
E   def hyp2f1b(x):
E       <source elided>
E                   return res
E               ii += 1
E               ^
E   
E   [1] During: typing of assignment at /home/juanlu/.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/hyper.py (26)
E   
E   File "../../../.miniconda36/envs/_test27_2/lib/python2.7/site-packages/poliastro/hyper.py", line 26:
E   def hyp2f1b(x):
E       <source elided>
E                   return res
E               ii += 1
E               ^
=============================================== warnings summary ===============================================
<undetermined location>
  passing a string to pytest.main() is deprecated, pass a list of arguments instead.

-- Docs: http://doc.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================== 1 warnings, 3 error in 2.67 seconds ======================================
```

Which means that, probably, the numba version is too new and something broke in the middle.

**Comment by Juanlu001** [comment]
*But*, poliastro 0.5.0 was already Python 3 only, and poliastro 0.4.0 didn't even correctly specify the pip dependencies because we were using conda back then. Manually installing astropy<1 and an old numba version did the trick.

**Comment by Juanlu001** [comment]
On the other hand, if one downgrades pip to <9, a different error occurs:

```
$ pip install poliastro
Collecting poliastro
  Downloading https://files.pythonhosted.org/packages/91/a5/1a67a7df553085f1c81acf1d5d105b18f1566636e8d1bf412b2750b4be29/poliastro-0.9.1.tar.gz (2.8MB)
    100% |████████████████████████████████| 2.8MB 207kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-QGipVt/poliastro/setup.py", line 76, in <module>
        long_description=open('README.rst', encoding='utf-8').read(),
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QGipVt/poliastro/
You are using pip version 8.1.2, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by Juanlu001** [comment]
So, for PyPI packages, we're kind of covered because pip 9 produces a proper error, and pip 8 at least does not install poliastro which will give a hint that there's something wrong. The situation is less than ideal, but I don't want to go and fix versions back to 2015.

On the other hand, conda packages are utterly broken and should be fixed. Probably the problems started with the `noarch` change, so we won't have to fix lots of versions.

**Comment by Juanlu001** [comment]
Flash news: I've been publishing poliastro conda packages that would cleanly install on Python 2 but miserably fail for **years**. We dropped support for Python 2 more than two years ago, and all versions of poliastro in conda-forge are broken.

This will require some time.

**Comment by Juanlu001** [comment]
...and I'm not even sure we will be able to remove all these bad releases. I'm removing the milestone, in case we have to focus on other things.
