### ISSUE TITLE
Cowell method fails to converge with small perturbation accelerations

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#367]
🐞 **Problem**

This code converges normally:

```
from astropy import units as u

from poliastro.twobody import Orbit
from poliastro.bodies import Earth
from poliastro.twobody.propagation import cowell

from poliastro.bodies import Body
from poliastro.twobody.rv import RVState

r0 = [-2384.46, 5729.01, 3050.46] * u.km
v0 = [-7.36138, -2.98997, 1.64354] * u.km / u.s

initial = Orbit.from_vectors(Earth, r0, v0)

def accel(t0, state, k):
    v_vec = state[3:]
    norm_v = (v_vec * v_vec).sum() ** .5
    return 1e-5 * v_vec / norm_v

print(initial.propagate(3 * u.day, method=cowell, ad=accel))
```

But changing to `1e-6 * v_vec / norm_v` fails to converge:

```
$ python ex0.py 
/home/juanlu/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/scipy/integrate/_ode.py:1095: UserWarning: dop853: larger nmax is needed
  self.messages.get(istate, unexpected_istate_msg)))
Traceback (most recent call last):
  File "ex0.py", line 20, in <module>
    print(initial.propagate(3 * u.day, method=cowell, ad=accel))
  File "/home/juanlu/Development/poliastro/poliastro-library/src/poliastro/twobody/orbit.py", line 271, in propagate
    return propagate(self, time_of_flight, method=method, rtol=rtol, **kwargs)
  File "/home/juanlu/Development/poliastro/poliastro-library/src/poliastro/twobody/propagation.py", line 209, in propagate
    r, v = method(orbit, time_of_flight.to(u.s).value, rtol=rtol, **kwargs)
  File "/home/juanlu/Development/poliastro/poliastro-library/src/poliastro/twobody/propagation.py", line 103, in cowell
    raise RuntimeError("Integration failed")
RuntimeError: Integration failed
```

🖥 **Please paste the output of following commands**

`pip freeze | grep astropy`

astropy==3.0.2

`pip freeze | grep poliastro`

-e git+git@github.com:Juanlu001/poliastro.git@34a9e2c83cd77e918feb0182d2fa162ba06cbd07#egg=poliastro

🎯 **Goal**

I would expect a zero perturbation acceleration to be equivalent to a keplerian orbit.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
The current API fails with this case:

```
def accel(t0, state, k):
    v_vec = state[3:]
    norm_v = (v_vec * v_vec).sum() ** .5
    return 0.0 * v_vec / norm_v
```

Can you add a corresponding test to #368 to see if the new solvers pass?
