### ISSUE TITLE
pip install fails with 0.10.0

### ISSUE THREAD

**Issue by camisatx** [poliastro/poliastro#417]
Hey Juan, thank you immensely for creating and actively maintaining this fantastic library!

I noticed that pip is not able to install the latest 0.10.0 release on the Anaconda 5.2.0 base, however, `pip install poliastro==0.9.2` works without any issue.

Running `pip install poliastro` fails to uninstall llvmlite, as specified in the following message:
```
Installing collected packages: llvmlite, numba
  Found existing installation: llvmlite 0.23.1
Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
It appears that installing poliastro via `conda install poliastro --channel conda-forge` works with all unittests working (except 3 that rely on matplotlib; running headless so that's expected), but I received a weird numpy issue when running an Orbit.propagate(date) command:
```
Traceback (most recent call last):
  File "test.py", line 240, in <module>
    calc()
  File "test.py", line 234, in calc
    d = orb.distance_to(test_date)
  File "test.py", line 65, in distance_to
    obj = obj.propagate(time)
  File "Anaconda_520/lib/python3.6/site-packages/poliastro/twobody/orbit.py", line 282, in propagate
    return propagate(self, time_of_flight, method=method, rtol=rtol, **kwargs)
  File "Anaconda_520/lib/python3.6/site-packages/poliastro/twobody/propagation.py", line 167, in propagate
    r, v = method(orbit, time_of_flight.to(u.s).value, rtol=rtol, **kwargs)
  File "Anaconda_520/lib/python3.6/site-packages/poliastro/twobody/propagation.py", line 119, in mean_motion
    return mean_motion_fast(k, r0, v0, tof)
  File "Anaconda_520/lib/python3.6/site-packages/numba/dispatcher.py", line 344, in _compile_for_args
    reraise(type(e), e, None)
  File "Anaconda_520/lib/python3.6/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed at nopython (nopython frontend)
Failed at nopython (nopython frontend)
Failed at nopython (nopython frontend)
Unknown attribute 'dot' of type array(float64, 1d, C)

File "Anaconda_520/lib/python3.6/site-packages/poliastro/core/util.py", line 86:
def norm(vec):
    <source elided>
    vec = 1.0 * vec  # Cast to float
    return np.sqrt(vec.dot(vec))
    ^

[1] During: typing of get attribute at /home/josh/Programming/Python/Anaconda_520/lib/python3.6/site-packages/poliastro/core/util.py (86)

File "../../../../../../Python/Anaconda_520/lib/python3.6/site-packages/poliastro/core/util.py", line 86:
def norm(vec):
    <source elided>
    vec = 1.0 * vec  # Cast to float
    return np.sqrt(vec.dot(vec))
    ^

[1] During: resolving callee type: type(CPUDispatcher(<function norm at 0x7f986e5980d0>))
[2] During: typing of call at /home/josh/Programming/Python/Anaconda_520/lib/python3.6/site-packages/poliastro/core/elements.py (110)


File "../../../../../../Python/Anaconda_520/lib/python3.6/site-packages/poliastro/core/elements.py", line 110:
def rv2coe(k, r, v, tol=1e-8):
    <source elided>
    h = cross(r, v)
    n = cross([0, 0, 1], h) / norm(h)
    ^

[1] During: resolving callee type: type(CPUDispatcher(<function rv2coe at 0x7f986e598d90>))
[2] During: typing of call at /home/josh/Programming/Python/Anaconda_520/lib/python3.6/site-packages/poliastro/core/propagation.py (32)


File "../../../../../../Python/Anaconda_520/lib/python3.6/site-packages/poliastro/core/propagation.py", line 32:
def mean_motion(k, r0, v0, tof):
    <source elided>
    # get the initial true anomaly and orbit parameters that are constant over time
    p, ecc, inc, raan, argp, nu0 = rv2coe(k, r0, v0)
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

I verified this on a fresh install of Anaconda, too.

Let me know if you have any questions, and keep up the fantastic work! :)

**Comment by Juanlu001** [comment]
Hi @camisatx, thanks for your interest and kind words! I'm from my smartphone at the moment but I suspect that you had numba installed with conda, and perhaps that's the reason why pip install can't upgrade the numba version. On the other hand, I think I did not upgrade the minimum required numba version in the conda-forge package and that might be the reason for the second failure. Could you please try to upgrade (using conda, I suppose) numba to the latest version (0.39) and try again? Will work on a fix this evening. Thanks again!

**Comment by camisatx** [comment]
You are right @Juanlu001 , pip could not upgrade numba. However, I had to run `conda install numba=0.39.0` to force it to upgrade to the latest numba release since `conda update numba` did not pull numba to 0.39.0.

Once numba was updated to 0.39.0, `pip install poliastro` worked without a hitch, installing version 0.10.0. This closes the first issue I experienced.

Again, this is coming from a new Anaconda install (which includes [numba 0.38.0](https://docs.anaconda.com/anaconda/packages/py3.6_linux-64)), so updating numba might be required (for Anaconda installs) until we get the next Anaconda release in Sep or so.

I ran a fresh conda install and it never updated numba, so I think you are right about forgetting to upgrade the minimum numba version in conda-forge. Once you set that, this issue can be closed. :)

Thanks for your very quick reply, too!

**Comment by Juanlu001** [comment]
Glad to know it finally worked! The fix is underway at https://github.com/conda-forge/poliastro-feedstock/pull/21 and I will merge as soon as the tests pass, so I'm closing this for the moment. The new package should be uploaded in about an hour. Feel free to comment here if the problem persists!
