### ISSUE TITLE
Debian packaging of poliastro 0.10.0/0.11b1

### ISSUE THREAD

**Issue by olebole** [poliastro/poliastro#453]
Hi,

as one of the affiliated packages, I am currently [trying to package poliastro](https://bugs.debian.org/908659) for Debian (from there it will migrate to Ubuntu, Mint etc.). For this, I have some questions, which don't fit into your template (so I took the freedom to not use it ;-) )

The Debian package will have its own [git repository](https://salsa.debian.org/debian-astro-team/poliastro.git), which basically has the latest poliastro release, and a `debian/` subdirectory containing all Debian specific things (build and install instructions, patches etc.). I already created the first files there for initial tests.

* Do I really need numba? Numba seems to be a flaky in Debian (has a [number of RC bugs](https://bugs.debian.org/cgi-bin/pkgreport.cgi?archive=no&pend-exc=pending-fixed&pend-exc=fixed&pend-exc=done&sev-inc=critical&sev-inc=grave&sev-inc=serious&repeatmerged=no&src=numba)), so I would llike to avoid it as a strong dependency. Without numba, I get the following error (both 0.10 and 0.11b1):
```
_________________________ test_no_numba_emits_warning __________________________

recwarn = WarningsRecorder(record=True)

    def test_no_numba_emits_warning(recwarn):
>       with _fake_numba_import():

poliastro/tests/test_jit.py:54: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.7/contextlib.py:112: in __enter__
    return next(self.gen)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @contextmanager
    def _fake_numba_import():
[…]
>       del sys.modules['numba']
E       KeyError: 'numba'

poliastro/tests/test_jit.py:28: KeyError
```

* Do I need jplephem? This is not in Debian yet, and it seems to be used only in `test_pertubations.py` (indirectly, via `astropy.coordinates.solar_system_ephemeris`). Removing the `solar_system_ephemeris('de432s')` calls just results in three failures due to the missing ~~~Moon~~~ Pluto *(in 0.11b1)* in the default approximation (which I could easily disable).

* I get the following white space failure (both 0.10 and 0.11b1):
```
____________________ [doctest] poliastro.maneuver.Maneuver _____________________
012 Class to represent a Maneuver.
013 
014     Each ``Maneuver`` consists on a list of impulses \\(\\Delta v_i\\)
015     (changes in velocity) each one applied at a certain instant \\(t_i\\).
016     You can access them directly indexing the ``Maneuver`` object itself.
017 
018     >>> man = Maneuver((0 * u.s, [1, 0, 0] * u.km / u.s),
019     ... (10 * u.s, [1, 0, 0] * u.km / u.s))
020     >>> man[0]
Expected:
    (<Quantity 0 s>, <Quantity [1,0,0] km / s>)
Got:
    (<Quantity 0. s>, <Quantity [1., 0., 0.] km / s>)

/build/poliastro-0.10.0/.pybuild/cpython3_3.7/build/poliastro/maneuver.py:20: DocTestFailure
```

* ~~~The `test_show_calls_prepare_plot` cannot be run in an automated test~~~ (not in 0.11b1)

* ~~~I get a problem (`numpy.float64`) with a conversion in the doctest~~~ (not in 0.11b1)

* One import statement is missing in a doctest (only in 0.11b1):
```
__________________ [doctest] poliastro.twobody.angles.M_to_nu __________________
276     delta : float (optional)
277         threshold of near-parabolic regime definition (from Davide Farnocchia et al)
278     Returns
279     -------
280     nu : float
281         True anomaly (rad).
282 
283     Examples
284     --------
285     >>> nu = M_to_nu(np.radians(30.0), 0.06)
UNEXPECTED EXCEPTION: NameError("name 'np' is not defined")
Traceback (most recent call last):

  File "/usr/lib/python3.7/doctest.py", line 1329, in __run
    compileflags, 1), test.globs)

  File "<doctest poliastro.twobody.angles.M_to_nu[0]>", line 1, in <module>

NameError: name 'np' is not defined

/build/poliastro-0.11~b1/.pybuild/cpython3_3.7/build/poliastro/twobody/angles.py:285: UnexpectedException
```

* Another missing import (only in 0.11b1):
```
_____________ [doctest] poliastro.twobody.orbit.Orbit.represent_as _____________
296             (859.07256, -4137.20368, 5295.56871)
297          (has differentials w.r.t.: 's')>
298         >>> iss.represent_as(CartesianRepresentation).xyz
299         <Quantity [  859.07256, -4137.20368,  5295.56871] km>
300         >>> iss.represent_as(CartesianRepresentation).differentials['s']
301         <CartesianDifferential (d_x, d_y, d_z) in km / s
302             (7.37289205, 2.08223573, 0.43999979)>
303         >>> iss.represent_as(CartesianRepresentation).differentials['s'].d_xyz
304         <Quantity [7.37289205, 2.08223573, 0.43999979] km / s>
305         >>> iss.represent_as(SphericalRepresentation)
UNEXPECTED EXCEPTION: NameError("name 'SphericalRepresentation' is not defined")
Traceback (most recent call last):

  File "/usr/lib/python3.7/doctest.py", line 1329, in __run
    compileflags, 1), test.globs)

  File "<doctest poliastro.twobody.orbit.Orbit.represent_as[6]>", line 1, in <module>

NameError: name 'SphericalRepresentation' is not defined

/build/poliastro-0.11~b1/.pybuild/cpython3_3.7/build/poliastro/twobody/orbit.py:305: UnexpectedException
```

* And another doctest failure (both 0.10 and 0.11b1):
```
________________ [doctest] poliastro.twobody.orbit.Orbit.sample ________________
303         -----
304         When specifying a number of points, the initial and final
305         position is present twice inside the result (first and
306         last row). This is more useful for plotting.
307 
308         Examples
309         --------
310         >>> from astropy import units as u
311         >>> from poliastro.examples import iss
312         >>> iss.sample()
Expected nothing
Got:
    (<Time object: scale='utc' format='iso' value=['2013-03-18 11:48' '2013-03-18 11:48' '2013-03-18 11:49'
     '2013-03-18 11:50' '2013-03-18 11:51' '2013-03-18 11:52'
[… more, one entry each minute …]
     '2013-03-18 11:48']>, <CartesianRepresentation (x, y, z) in km
        [(-4136.38403782, -4179.52820669,  3358.86048469),
         (-3804.53435268, -4281.55527653,  3613.04813899),
[… more lines …]
         (-4136.38403782, -4179.52820669,  3358.86048469)]>)

/build/poliastro-0.10.0/.pybuild/cpython3_3.7/build/poliastro/twobody/orbit.py:312: DocTestFailure
```

Can you help me with that? And/or would you like to co-maintain or take over the packaging (I would gladly help with any problems that may appear)?

The current environment: Python 3.7 (and 3.6), numpy 1.14.
**[Update]** I now upgraded to 0.11b1, and updated the list above accordingly.

**Comment by Juanlu001** [comment]
Hi @olebole, sorry for the late reply and thanks a lot for this! It's amazing that poliastro is about to be available in Debian with some effort. I will be away from the computer all these days, but let me respond your concerns:

* numba is optional, so the test failure is a bug.
* jplephem is optional and probably should be marked as such, I have to go and see whether Astropy already depends on it.
* I never run the doctests so all the failures you report are bugs.

I will try to fix everything before 0.11 final release so we have a good candidate to include in Debian. What do you think?

Thanks again!

**Comment by olebole** [comment]
@Juanlu001 That sounds like a good plan :-)

Astropy does not depend on jplephem, but lists it as optional package. I could think of packaging it for Debian, but I first would have to check how the JPL data download fits into the Debian ecosystem -- mainly license issues with the JPL data worry me here. This I would like to avoid for the moment.

**Comment by Juanlu001** [comment]
@olebole I have given this some thought and I think I will focus on fixing the doctest issues for this release (some more bugs surfaced since I started running them, see #454) but for making some dependencies optional I will need some more time (https://github.com/poliastro/poliastro/issues/168#issuecomment-421963430). The following release should arrive not later than March next year https://github.com/poliastro/poliastro/milestone/12, so I will ping you here when I sort that out.

**Comment by olebole** [comment]
OK; thanks. just to be sure: *are* jplephem and numba currently optional (and I could just make the tests xfail), or will one run into trouble when they are not installed?

For the timeline: we will have our freeze for the next Debian release (Buster) in February and March 2019 (full freeze on March 12); so I would basically try to get poliastro in ASAP (it takes some time to get the package reviewed for licensing and our policy compliance), and then fix the rest. Therefore, if jplephem is not strictly needed, I would disable the failing test, and then either use numba as dependency, or disable this test as well. I could even disable the doctests for the moment.

An early upload would also help me to sort our potential integration problems and to provide some feedback, f.e. with newer versions of the dependencies (we run the tests on every dependency change).

**Comment by olebole** [comment]
That sounds like a very good plan to me! Thank you very much for helping me!

**Comment by Juanlu001** [comment]
@olebole, https://github.com/poliastro/poliastro/pull/454 should fix all the issues you reported, in case you already want to try. Windows builds are broken because matplotlib 3.0 wheels are not yet available.

**Comment by olebole** [comment]
I can confirm that the patches work very well. When I also remove the Pluto tests (see #458), all tests pass and the package builds nicely. So, I will just wait for the official release of 0.11 ;-)

**Comment by olebole** [comment]
After testing 0.11.0, everything works fine for me. I can build it (and test with Python 3.6/3.7) without the need of any patch. So, thank you very much!!! I will now upload; it may however take a while until it is reviewed by our ftp-masters.

**Comment by Juanlu001** [comment]
Just saw that the upstream issue has been closed:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908659

There's also this tweet:

https://twitter.com/DebianAstro/status/1044605531804061697?s=19

As far as I understand it's not 100 % ready yet:

https://blends.debian.org/astro/tasks/python3

So I prefer to wait until we can effectively apt-install it :)

**Comment by olebole** [comment]
The upstream issue is automatically closed when it was uploaded to "unstable". It will stay there for ~7 days, and if there are no release critical bugs (and the CI test passes), it will migrate to "testing". "Testing" will become the new Debian 10 "Buster" release next year.
So, a simple `apt install python3-poliastro` will work only then, you still need some patience.
What we could do (once it migrated to `testing`) is to do a "backport" to Debian Stretch. This is not that complicated; however since my own resources are limited, I don't want to do it myself.
But since there was such a positive response on the announcement on Twitter: maybe one of you wants to jump in here? It would also be great if someone would help me co-maintaining the package (and get write access to [salsa](https://salsa.debian.org/debian-astro-team/poliastro)).

Some links:
* The package maintainer's page https://tracker.debian.org/pkg/poliastro
* The page for the binary package in unstable, `python3-poliastro`https://packages.debian.org/unstable/python3-poliastro
* The page for the source package in unstable, https://packages.debian.org/source/unstable/poliastro
* The bugs page for poliastro https://bugs.debian.org/src:poliastro
* The Git repository for the package https://salsa.debian.org/debian-astro-team/poliastro
* The Ubuntu launchpad page https://launchpad.net/ubuntu/+source/poliastro

Most of them are still not available; they are going to be filled in the next days. Also, the blends pages (and the sources where the information there comes from) is updated only a bit slowly; that's why it shows the outdated status of yesterday. Will change tomorrow or so.

**Comment by Juanlu001** [comment]
> So, a simple apt install python3-poliastro will work only then, you still need some patience.

We will patiently wait :)

> What we could do (once it migrated to testing) is to do a "backport" to Debian Stretch.

If I understand correctly, the Astropy version in Stretch is 1.3:

https://packages.debian.org/stretch/python3-astropy

And poliastro requires >= 3.0:

https://github.com/poliastro/poliastro/blob/d7fb686b56c95812350772d18a6e80793dc7fc0d/setup.py#L29

Does it still make sense?

**Comment by Juanlu001** [comment]
Thanks for answering these dumb questions, I am learning a lot about how Debian works :)

I didn't know that there was this sort of deadline to do the non-security backports, so I assumed we could do it during the "support" period (but I also think I misunderstood the support calendar for Stretch).

**Comment by Juanlu001** [comment]
Just checked that the package is available! :tada: 

https://packages.debian.org/sid/python3-poliastro

There will be more bugs we might need to backport (I'm thinking of #471) but the initial process is done, so I think we can close this. If there's anything else I can do to help please ping me. Thanks a lot!
