### ISSUE TITLE
Improve ephemerides error appearance

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#705]
```
>>> laplace_radius(Moon)
Traceback (most recent call last):
  File "/home/juanlu/Development/poliastro/poliastro-library/src/poliastro/twobody/orbit.py", line 396, in from_body_ephem
    r, v = get_body_barycentric_posvel(body.name, epoch)
  File "/home/juanlu/.miniconda36/envs/poliastro37/lib/python3.7/site-packages/astropy/coordinates/solar_system.py", line 330, in get_body_barycentric_posvel
    return _get_body_barycentric_posvel(body, time, ephemeris)
  File "/home/juanlu/.miniconda36/envs/poliastro37/lib/python3.7/site-packages/astropy/coordinates/solar_system.py", line 225, in _get_body_barycentric_posvel
s    "the '{0}' ephemeris.".format(ephemeris))
KeyError: "the Moon's velocity cannot be calculated with the 'builtin' ephemeris."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/.miniconda36/envs/poliastro37/lib/python3.7/site-packages/astropy/utils/decorators.py", line 860, in laplace_radius
    func = make_function_with_signature(func, name=name, **wrapped_args)
  File "/home/juanlu/.miniconda36/envs/poliastro37/lib/python3.7/site-packages/astropy/units/decorators.py", line 222, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)
  File "/home/juanlu/Development/poliastro/poliastro-library/src/poliastro/threebody/soi.py", line 55, in laplace_radius
    a = Orbit.from_body_ephem(body, J2000_TDB).a
  File "/home/juanlu/Development/poliastro/poliastro-library/src/poliastro/twobody/orbit.py", line 399, in from_body_ephem
    "To compute the position and velocity of the Moon and Pluto use the JPL ephemeris:\n>>>from astropy.coordinates import solar_system_ephemeris\n>>>solar_system_ephemeris.set('jpl')"
RuntimeError: To compute the position and velocity of the Moon and Pluto use the JPL ephemeris:
```

**Comment by Juanlu001** [comment]
Fixed in #723.
